const mockData = [
  {
    id: 600018821,
    productName: 'Gold Necklace',
    address: 'Nishant Apartment Roha, Raigad 402109',
    date: '2024-11-01',
    price: 100,
    status: 'Pending',
    customerName: 'John Doe',
    customerPhone: '9876543210',
    paymentMethod: 'Credit Card',
    shippingMethod: 'Standard Shipping',
  },
  {
    id: 213,
    productName: 'Diamond Ring',
    address: 'Gayatri A DP road, Pune',
    date: '2024-11-02',
    price: 200,
    status: 'Completed',
    customerName: 'Alice Smith',
    customerPhone: '9123456789',
    paymentMethod: 'PayPal',
    shippingMethod: 'Express Shipping',
  },
  {
    id: 312,
    productName: 'Silver Bracelet',
    address: 'Hadapsar, Pune',
    date: '2024-11-03',
    price: 300,
    status: 'Cancelled',
    customerName: 'Bob Johnson',
    customerPhone: '9876512345',
    paymentMethod: 'Debit Card',
    shippingMethod: 'Economy Shipping',
  },
  {
    id: 1001,
    productName: 'Pearl Earrings',
    address: 'Kalyani Nagar, Pune',
    date: '2024-11-04',
    price: 150,
    status: 'Completed',
    customerName: 'Emma White',
    customerPhone: '9967458790',
    paymentMethod: 'Bank Transfer',
    shippingMethod: 'Overnight Shipping',
  },
  {
    id: 1002,
    productName: 'Platinum Band',
    address: 'Baner Road, Pune',
    date: '2024-11-05',
    price: 1200,
    status: 'Pending',
    customerName: 'Liam Brown',
    customerPhone: '9765312468',
    paymentMethod: 'Credit Card',
    shippingMethod: 'Standard Shipping',
  },
  {
    id: 1023,
    productName: 'Gold Bangle',
    address: 'Bangalore, Karnataka',
    date: '2024-11-06',
    price: 250,
    status: 'Completed',
    customerName: 'Ravi Patel',
    customerPhone: '9876554321',
    paymentMethod: 'Debit Card',
    shippingMethod: 'Standard Shipping',
  },
  {
    id: 2045,
    productName: 'Diamond Pendant',
    address: 'Mumbai, Maharashtra',
    date: '2024-11-07',
    price: 500,
    status: 'Pending',
    customerName: 'Neha Agarwal',
    customerPhone: '9988776655',
    paymentMethod: 'Credit Card',
    shippingMethod: 'Express Shipping',
  },
  {
    id: 4567,
    productName: 'Ruby Necklace',
    address: 'Chennai, Tamil Nadu',
    date: '2024-11-08',
    price: 450,
    status: 'Cancelled',
    customerName: 'Suresh Kumar',
    customerPhone: '9876432112',
    paymentMethod: 'PayPal',
    shippingMethod: 'Economy Shipping',
  },
  {
    id: 8901,
    productName: 'Sapphire Ring',
    address: 'Delhi',
    date: '2024-11-09',
    price: 1200,
    status: 'Completed',
    customerName: 'Priya Singh',
    customerPhone: '8765432109',
    paymentMethod: 'Bank Transfer',
    shippingMethod: 'Overnight Shipping',
  },
  {
    id: 1020,
    productName: 'Emerald Earrings',
    address: 'Hyderabad, Telangana',
    date: '2024-11-10',
    price: 700,
    status: 'Pending',
    customerName: 'Rajesh Mehra',
    customerPhone: '9001122334',
    paymentMethod: 'Debit Card',
    shippingMethod: 'Express Shipping',
  },
  {
    id: 3045,
    productName: 'Gold Chain',
    address: 'Kochi, Kerala',
    date: '2024-11-11',
    price: 300,
    status: 'Completed',
    customerName: 'Aditi Verma',
    customerPhone: '9898123456',
    paymentMethod: 'Credit Card',
    shippingMethod: 'Economy Shipping',
  },
  {
    id: 5067,
    productName: 'Platinum Pendant',
    address: 'Pune, Maharashtra',
    date: '2024-11-12',
    price: 30,
    status: 'Pending',
    customerName: 'Kiran Kumar',
    customerPhone: '9887766554',
    paymentMethod: 'PayPal',
    shippingMethod: 'Standard Shipping',
  },
  {
    id: 6089,
    productName: 'Silver Anklet',
    address: 'Indore, Madhya Pradesh',
    date: '2024-11-13',
    price: 25,
    status: 'Cancelled',
    customerName: 'Sneha Desai',
    customerPhone: '9845678923',
    paymentMethod: 'Credit Card',
    shippingMethod: 'Express Shipping',
  },
  {
    id: 7890,
    productName: 'Diamond Studs',
    address: 'Gurgaon, Haryana',
    date: '2024-11-14',
    price: 100,
    status: 'Completed',
    customerName: 'Vikas Arora',
    customerPhone: '9876543212',
    paymentMethod: 'Debit Card',
    shippingMethod: 'Overnight Shipping',
  },
];

export default mockData;
